# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeLoop <- function(m, v, w, C, A, B, Wsx, paramList) {
    invisible(.Call('_PatchProcess34_computeLoop', PACKAGE = 'PatchProcess34', m, v, w, C, A, B, Wsx, paramList))
}

combineLabels <- function(Swx, Qwx, Rwx, S_height, Q_height, width) {
    invisible(.Call('_PatchProcess34_combineLabels', PACKAGE = 'PatchProcess34', Swx, Qwx, Rwx, S_height, Q_height, width))
}

computeMerge <- function(A, Asizes, B, Bsizes, Twx, Jt, paramList) {
    invisible(.Call('_PatchProcess34_computeMerge', PACKAGE = 'PatchProcess34', A, Asizes, B, Bsizes, Twx, Jt, paramList))
}

computeContext <- function(Jt_v, Cont_v, ContOrder_v, number_of_labels, number_of_merged_labels) {
    invisible(.Call('_PatchProcess34_computeContext', PACKAGE = 'PatchProcess34', Jt_v, Cont_v, ContOrder_v, number_of_labels, number_of_merged_labels))
}

applySyntax <- function(Twx_v, Gtt_v, Jt_v, Gt_v, Uwx_v, Axw_v, Axu_v, number_of_syntax_labels, number_of_labels, number_of_patches, number_of_images) {
    invisible(.Call('_PatchProcess34_applySyntax', PACKAGE = 'PatchProcess34', Twx_v, Gtt_v, Jt_v, Gt_v, Uwx_v, Axw_v, Axu_v, number_of_syntax_labels, number_of_labels, number_of_patches, number_of_images))
}

